stages:
  - test
  - deploy-staging
  - deploy-production

default:
  image: node:20-bullseye

test:
  stage: test
  variables:
    JEST_JUNIT_OUTPUT_NAME: junit.xml
  before_script:
    - apt-get update -qq && apt-get install --no-install-recommends -y build-essential python3 pkg-config libvips-dev poppler-utils libsqlite3-dev
  script:
    - npm ci --ignore-scripts
    - npm_config_build_from_source=true npm rebuild sqlite3
    - npm rebuild sharp
    - npm run coverage -- --coverageReporters=cobertura --coverageReporters=text
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    expire_in: 7 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-staging:
  stage: deploy-staging
  needs: [test]
  script:
    - curl -L https://fly.io/install.sh | sh
    - export PATH="$HOME/.fly/bin:$PATH"
    - fly deploy --config fly.staging.toml --access-token "FlyV1 $FLY_API_TOKEN"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-production:
  stage: deploy-production
  needs: [deploy-staging]
  script:
    - curl -L https://fly.io/install.sh | sh
    - export PATH="$HOME/.fly/bin:$PATH"
    - fly deploy --config fly.toml --access-token "FlyV1 $FLY_API_TOKEN"
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
